required = [
    "github.com/emicklei/go-restful",
    "github.com/onsi/ginkgo", # for test framework
    "github.com/onsi/gomega", # for test matchers
    "k8s.io/client-go/plugin/pkg/client/auth/gcp", # for development against gcp
    "k8s.io/code-generator/cmd/deepcopy-gen", # for go generate
    "sigs.k8s.io/controller-tools/cmd/controller-gen", # for crd/rbac generation
    "sigs.k8s.io/controller-runtime/pkg/client/config",
    "sigs.k8s.io/controller-runtime/pkg/controller",
    "sigs.k8s.io/controller-runtime/pkg/handler",
    "sigs.k8s.io/controller-runtime/pkg/manager",
    "sigs.k8s.io/controller-runtime/pkg/runtime/signals",
    "sigs.k8s.io/controller-runtime/pkg/source",
    "sigs.k8s.io/testing_frameworks/integration", # for integration testing
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1",
    "github.com/shurcooL/vfsgen", # Because this is used by assets_generate.sh
    ]

ignored = [
  "github.com/googleapis/gnostic/plugins/gnostic-go-generator/examples*",
  "sigs.k8s.io/controller-tools/pkg/crd/generator/testData*",
]

[prune]
  go-tests = true

[[override]]
name = "sigs.k8s.io/controller-runtime"
source = "https://github.com/coderanger/controller-runtime.git"
branch = "crd-update-0.1"

[[override]]
name = "github.com/coreos/prometheus-operator"
source = "https://github.com/coderanger/prometheus-operator.git"
branch = "openapi-wat"

# STANZAS BELOW ARE GENERATED AND MAY BE WRITTEN - DO NOT MODIFY BELOW THIS LINE.

[[constraint]]
  name="sigs.k8s.io/controller-runtime"
  version="v0.1.12"

[[constraint]]
  name="sigs.k8s.io/controller-tools"
  version="v0.1.10"
  
[[constraint]]
  name="github.com/gobuffalo/envy"
  version="v1.6.15"

# For dependency below: Refer to issue https://github.com/golang/dep/issues/1799
[[override]]
name = "gopkg.in/fsnotify.v1"
source = "https://github.com/fsnotify/fsnotify.git"
version="v1.4.7"
